-- Add the column
ALTER TABLE math_problem_sessions
ADD COLUMN IF NOT EXISTS solution_steps TEXT;

-- Add comment for documentation
COMMENT ON COLUMN math_problem_sessions.solution_steps IS 
'Step-by-step solution generated by AI when problem is created';

-- Verify the migration
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_name = 'math_problem_sessions' 
    AND column_name = 'solution_steps'
  ) THEN
    RAISE NOTICE '✅ Migration successful: solution_steps column added';
  ELSE
    RAISE NOTICE '❌ Migration failed: solution_steps column not found';
  END IF;
END $$;